### ISSUE TITLE
Unsolvable jax dependency

### ISSUE THREAD

**Issue by adiaconu11** [google-deepmind/acme#321]
Following the most recent commit, the jax.tree module is now being used instead of jax.tree_*. This is change requires jax >= 0.4.25. However, the are still many parts of the repository that are still old/deprecated. For instance, if you install 0.4.25 you might get something like:

`AttributeError: module 'jax.random' has no attribute 'KeyArray'`

This is because this module has been removed in jax 0.4.24, meaning that in order to not run into this problem you need jax <=0.4.23. Obviously this goes against the requirement above.

Lastly, there is still the issue with DeviceArray and ShardedDeviceArray. They have all been changed to somply jax.Array back in jax=0.4.0! At the current state of the repo you basically need to add lines like:

`jax.interpreters.xla.DeviceArray = jax.Array` in order to be able to even import acme...

**Comment by adiaconu11** [comment]
the jax.Array issue can be solved by installing chex==0.1.7 instead of the default 0.1.6. This should be updated in the requirements of acme.

**Comment by lkoelman** [comment]
Bumping into similar problems. It is very hard to install a functional stack.

**Comment by fload** [comment]
same couldn't get it installed in windows or Ubuntu

**Comment by TaroKingCN** [comment]
> same couldn't get it installed in windows or Ubuntu

have you solved it ?

**Comment by KiteAB98** [comment]
How to fix the error when executing this command:
pip install git+https://github.com/deepmind/acme.git#egg=dm-acme[jax,tf,envs] --use-deprecated=legacy-resolver   
  Traceback (most recent call last):
        File "/DATACENTER2/zpj/miniconda3/envs/diffdt/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
        File "/DATACENTER2/zpj/miniconda3/envs/diffdt/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
        File "/DATACENTER2/zpj/miniconda3/envs/diffdt/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 280, in build_wheel
          return _build_backend().build_wheel(
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 441, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 429, in _build
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 410, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 357, in <module>
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)  # type: ignore[return-value]
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 186, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 1000, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1107, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 1019, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/command/bdist_wheel.py", line 370, in run
          self.run_command("build")
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 341, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1107, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 1019, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 341, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1107, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-i14lqcyq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 1019, in run_command
          cmd_obj.run()
        File "<string>", line 154, in run
        File "<string>", line 190, in _find_mujoco
      RuntimeError: Cannot find MuJoCo library and/or include paths
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mujoco
Successfully built dm-acme
Failed to build mujoco
error: failed-wheel-build-for-install

× Failed to build installable wheels for some pyproject.toml based projects
╰─> mujoco
